{{- range .Values.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/name: http-echo
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ .name }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: http-echo
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-echo
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ .name }}
    spec:
      containers:
      - name: http-echo
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        args:
          - -listen=:{{ .port | default $.Values.service.port }}
          - -text={{ .text }}
        ports:
        - name: http
          containerPort: {{ .port | default $.Values.service.port }}
          protocol: TCP
        resources:
          {}
{{- end }}
