{{- range .Values.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/name: http-echo
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ .port | default $.Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: http-echo
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ .name }}
{{- end }}
